---
title: "Checking and tiding up the climate data"
author: "Junqi ZHU, Remi FRAYSSE"
output:
  html_document: default
---

```{r, warning=FALSE, echo=FALSE, tidy=TRUE, error=FALSE, message=FALSE}
 rm(list = ls())
    {
    library(plyr)
    l_ply(list('tidyverse','readxl','tidyr','dplyr','ggplot2','broom','ggthemes','plotly','purrr',
               'reshape2','cowplot','grid', 'reshape2','lubridate', 'RColorBrewer', 'datacheck'), 
          require, character.only = T)
    # tidyverse_update(recursive = FALSE) #updating packages
    #get the current working directory
    MainDir <- list(PROJHOME = normalizePath(getwd()))
    # Input and output directory data file location
    ExpData = file.path(MainDir, 'ExpData')
    # figure output directory, mainly the the place for paper writing 
    FigureOutput = file.path(MainDir, 'Figures')
    
    # Output directory, final results except figures, like statistics, and intermediate data set
    IntermediateResults = file.path(MainDir, 'Intermediate results')  
    SupportingFunctions = file.path(MainDir, 'Supporting functions')
    # CustomizedFunctions = file.path('d:/Programming language/R language/Customized function library/')
    CustomizedFunctions = file.path(MainDir, 'customizedFunctionsLib')
    # Load all functions
    source(file.path(CustomizedFunctions,'Customized_curve_fitting_functions.R'))
    source(file.path(CustomizedFunctions,'Customized_functions_data_reconstruction.R'))
    source(file.path(CustomizedFunctions,'Customized_functions_for_photosynthesis.R'))
    # 
    source(file.path(SupportingFunctions,'Layout_of_ggplot.R'))
    source(file.path(SupportingFunctions,'Specific_functions.R'))
    # lsf.str()  #list of functions
    } 
```

# A remind of the subject that you are working on
```{r}
current.region <- 'Hawkes_bay'
current.station <- 'LawnRoad'
current.subject <- 'Daily_MetData'

output.name <- paste(current.region, current.station, current.subject, sep = '_')
print(output.name)

```

## Load the data
```{r, warning=FALSE, echo=FALSE, error=FALSE, message=FALSE}

daily.data.24am <- 
  tbl_df(read_csv(file.path(ExpData, "Hawkes_Bay.csv"), col_names = T)) %>% 
  # select(year, day, date, max.temp, min.temp, total.rain, mean.wind.speed)
  rename(total.rain = rain, max.temp = maxt, min.temp = mint, radiation = radn)



daily.data.24am <- 
  select(daily.data.24am, -c(mean, vp, Station)) %>% 
  mutate_if(is.character, funs(as.numeric(as.character(.)))) %>% 
  filter(!is.na(year)) %>% 
  mutate(radiation = case_when(radiation > -0 ~ radiation)) %>% 
  rename(radn = radiation)
  

short_summary(daily.data.24am)

```

## create a complete records of days
```{r, warning=FALSE, echo=FALSE, error=FALSE, message=FALSE}
  first.day <- first(daily.data.24am$day)
  first.year <- first(daily.data.24am$year)
  last.day <- last(daily.data.24am$day)
  last.year <- last(daily.data.24am$year)
  
  start.date <- as.Date(first.day, origin = paste(first.year-1, 12, 31, sep = '-'))
  end.date <- as.Date(last.day, origin = paste(last.year-1, 12, 31, sep = '-'))
  start.date
  end.date
  # yday(end.date)
  
  complete.year.day <- 
    data_frame(date = seq.Date(from = start.date,to = end.date, by = 'day')) %>% 
    mutate(year = year(date), day.of.year = yday(date))
  
  glimpse(complete.year.day)
  glimpse(daily.data.24am)
  
```



# export the data
```{r, fig.width=15, fig.height=25,echo=FALSE}
# relative humidity data are mainly missing from the data


output.data <- 
daily.data.24am %>% 
  filter(!is.na(max.temp)) %>% 
  filter(max.temp > -50, min.temp > -50) %>% 
  mutate(year = format(year, scientific = FALSE)) %>% 
  ungroup() %>% 
  mutate(year = as.integer(year), day=as.integer(day)) %>%
  mutate(station = "LawnRoad")
  
short_summary(output.data)

output.data %>% 
  ggplot(aes(day, min.temp, colour=as.factor(year))) +
  facet_wrap(~as.factor(station)) +
  geom_point(size = 0.3) +
  theme(legend.title= element_text(size=0))

write_csv(output.data, file.path(IntermediateResults, paste(output.name, ".csv", sep = '')))

write_tsv(output.data, file.path(IntermediateResults, paste(output.name, ".met", sep = '')))



```





















