---
title: "Checking and tiding up the climate data"
author: "Junqi ZHU"
output:
  html_document: default
---

```{r, warning=FALSE, echo=FALSE, tidy=TRUE, error=FALSE, message=FALSE}
 rm(list = ls())
    {
    library(plyr)
    l_ply(list('tidyverse','readxl','tidyr','readr','dplyr','ggplot2','broom','ggthemes','plotly','purrr',
               'reshape2','cowplot','grid', 'reshape2','lubridate', 'RColorBrewer', 'datacheck'), 
          require, character.only = T)
    # tidyverse_update(recursive = FALSE) #updating packages
    #get the current working directory
    MainDir <- list(PROJHOME = normalizePath(getwd()))
    # Input and output directory data file location
    ExpData = file.path(MainDir, 'ExpData')
    # figure output directory, mainly the the place for paper writing 
    FigureOutput = file.path(MainDir, 'Figures')
    
    # Output directory, final results except figures, like statistics, and intermediate data set
    IntermediateResults = file.path(MainDir, 'Intermediate results')  
    SupportingFunctions = file.path(MainDir, 'Supporting functions')
    # CustomizedFunctions = file.path('d:/Programming language/R language/Customized function library/')
    IntermediateResults = file.path(MainDir, 'Intermediate results')  
    SupportingFunctions = file.path(MainDir, 'Supporting functions')
    # CustomizedFunctions = file.path('d:/Programming language/R language/Customized function library/')
    CustomizedFunctions = file.path('/powerplant/workspace/hrmjxz/Programming_lang/R_language/Function_library/')
    IntermediateResults = file.path(MainDir, 'Intermediate results')  
    SupportingFunctions = file.path(MainDir, 'Supporting functions')
    # Load all functions
    source(file.path(CustomizedFunctions,'Customized_functions_for_climate.R'))
    # lsf.str()  #list of functions
    } 
```

# A remind of the subject that you are working on
```{r}
current.region <- 'Waipara'
current.subject <- ''
site = "Waipara"
output.name <- paste(current.region, current.subject, sep = '')
output.name

```

## Load the data
```{r, warning=FALSE, echo=FALSE, error=FALSE, message=FALSE}
 waipara.data <- 
  read_csv(file.path(ExpData, 'Waipara daily new.csv')) 
 
 camshorm.data <- 
  read_csv(file.path(IntermediateResults, 'Camshorm_Hourly.daily.cal.csv')) 

```

## create a complete records of days

```{r, warning=FALSE, echo=FALSE, error=FALSE, message=FALSE}

first.day <- first(waipara.data$day)
first.year <- first(waipara.data$year)

last.day <- last(waipara.data$day)
last.year <- last(waipara.data$year)

start.date <- as.Date(first.day, origin = paste(first.year-1, 12, 31, sep = '-'))
end.date <- as.Date(last.day, origin = paste(last.year-1, 12, 31, sep = '-'))


yday(end.date)

complete.year.day <- 
  data_frame(date = seq.Date(from = start.date,to = end.date, by = 'day')) %>% 
  mutate(year = year(date), day = yday(date)) 


glimpse(complete.year.day)

```

# Check the missing data and replace missing value
```{r, fig.width=15, fig.height=25,echo=FALSE}
names(waipara.data)
 
waipara.data.new <- 
  right_join(waipara.data, complete.year.day, by = c('year','day')) %>% 
  mutate_at('rain', funs(replace(., .< 0, 0))) %>% 
  mutate_at('maxt',funs(replace(., .> 40, 40))) %>%  
  mutate_at('maxt',funs(replace(., .< 0, NA))) %>%  
  mutate_at('radn',funs(replace(., .< 0, 0))) %>% 
  mutate_at('wind',funs(replace(., .< 0, 0))) %>% 
  mutate_at('mint',funs(replace(., .< -15, NA))) %>% 
  mutate_at('vp',funs(replace(., .< 0, NA))) %>% 
  mutate_if(is.numeric,funs(replace(.,is.na(.),NA))) %>% 
 
  mutate_at("rain",funs(replace(.,is.na(.),mean(.,na.rm=TRUE))))%>%
  mutate_at("maxt",funs(replace(.,is.na(.),mean(.,na.rm=TRUE))))%>%
  mutate_at("mint",funs(replace(.,is.na(.),mean(.,na.rm=TRUE))))%>%
  mutate_at("radn",funs(replace(.,is.na(.),mean(.,na.rm=TRUE))))%>%
  mutate_at("wind",funs(replace(.,is.na(.),mean(.,na.rm=TRUE))))%>%
  mutate_at("vp",funs(replace(.,is.na(.),mean(.,na.rm=TRUE)))) %>% 
  
  distinct(year,day, .keep_all = TRUE) %>% 
  arrange(year,day) %>% 
  select(-mean, -maxt, -mint)
  
 
glimpse(waipara.data.new)

short_summary(waipara.data.new)  
 
  # View(waipara.data.hourly)
```
# combine with the camshorm daily data
```{r, fig.width=15, fig.height=25,echo=FALSE}
names(waipara.data)

 waipara.data.fin <- 
 left_join(waipara.data.new, camshorm.data, by= c('year', 'day')) %>% 
   rename(maxt =ta_max, mint=ta_min) %>% 
   mutate(meant = 0.5*(maxt+ mint)) %>% 
   select(year, day, rain, maxt, meant, mint, radn, wind, vp) %>% 
 
  rename(doy = day) %>% 
  mutate(vp= vp/10) %>% 
  mutate(RH = vp/satvap(meant)*100) %>% 
  mutate_at('RH', funs(replace(., .>100, 100))) %>%  
  mutate(vpd = satvap(meant)-vp) %>% 
  mutate_at('vpd', funs(replace(., .< 0, 0))) %>% 
  rename(Tmin = mint, 
         Tmax = maxt,
         Tmean = meant,
         totalRain = rain,
         Rad = radn, 
         Wind = wind) %>% 
  mutate(ET0 = calcDailyET0(Rad, Tmean, Wind, vpd)) %>% 
  mutate(ET_Rain = ET0 - totalRain) %>%
  mutate(station = site) %>% 
  mutate(vineyard = case_when(station == "Blenheim" ~ "NA",
                             TRUE ~ station)) %>% 
  mutate(region = current.region) %>% 
   select(-vp)
  

glimpse(waipara.data.fin)

short_summary(waipara.data.fin)  
 
  # View(waipara.data.hourly)
```

## Load the organized data
```{r, warning=FALSE, echo=FALSE, error=FALSE, message=FALSE}

 daily.data <- 
  read_csv(file.path(IntermediateResults, 'MetData_2020_5.csv'),guess_max = 1000)
  
  # filter(region !="Waipara")

glimpse(daily.data)

```

#join the data
```{r, fig.width=15, fig.height=25,echo=FALSE}

full.data <- 
    bind_rows(daily.data, waipara.data.fin) 
 

 #be careful with this code to avide adding errors to the data
  # write_csv(full.data, file.path(IntermediateResults, 'MetData_2020_5.csv'))

# write_tsv(full.data, file.path(IntermediateResults, paste(output.name, "met", sep = '.')))
glimpse(full.data)
```

#APSIM output
```{r, fig.width=15, fig.height=25,echo=FALSE}

apsim <- 
  full.data %>% 
  filter(station==site) %>% 
  select(year,doy,totalRain,Tmax, Tmin, Rad,Wind,RH,vpd) %>% 
  mutate(RH = round(RH, 2), vpd = round(vpd,2), Rad =round(Rad,2), Wind = round(Wind,2) )

glimpse(apsim)
write.table(apsim, file.path(IntermediateResults, paste(output.name, "met", sep = '.')), row.names = F, sep = ' ')

# write_tsv(full.data, file.path(IntermediateResults, paste(output.name, "met", sep = '.')))

```








