---
title: "Checking and tiding up the climate data"
author: "Junqi ZHU"
output:
  html_document: default
---

```{r, warning=FALSE, echo=FALSE, tidy=TRUE, error=FALSE, message=FALSE}
 rm(list = ls())
    {
    library(plyr)
    l_ply(list('tidyverse','readxl','tidyr','readr','dplyr','ggplot2','broom','ggthemes','plotly','purrr',
               'reshape2','cowplot','grid', 'reshape2','lubridate', 'RColorBrewer', 'datacheck'), 
          require, character.only = T)
    # tidyverse_update(recursive = FALSE) #updating packages
    #get the current working directory
    MainDir <- list(PROJHOME = normalizePath(getwd()))
    # Input and output directory data file location
    ExpData = file.path(MainDir, 'ExpData')
    # figure output directory, mainly the the place for paper writing 
    FigureOutput = file.path(MainDir, 'Figures')
    
    # Output directory, final results except figures, like statistics, and intermediate data set
    IntermediateResults = file.path(MainDir, 'Intermediate results')  
    SupportingFunctions = file.path(MainDir, 'Supporting functions')
    # CustomizedFunctions = file.path('d:/Programming language/R language/Customized function library/')
    CustomizedFunctions = file.path(MainDir, 'customizedFunctionsLib')
    
    # Load all functions
    source(file.path(CustomizedFunctions,'Customized_curve_fitting_functions.R'))
    source(file.path(CustomizedFunctions,'Customized_functions_data_reconstruction.R'))
    
    source(file.path(SupportingFunctions,'Layout_of_ggplot.R'))
    source(file.path(SupportingFunctions,'Specific_functions.R'))
    # lsf.str()  #list of functions
    } 
```

# A remind of the subject that you are working on
```{r}
current.region <- 'Site1002_OYB'
current.subject <- 'Hourly_New'
# current.year <- '18_19'

output.name <- paste(current.region, current.subject, sep = '_')
output.name

```

## Load the data
```{r, warning=FALSE, echo=FALSE, error=FALSE, message=FALSE}
options(dplyr.width = Inf, dplyr.print_min = 10)

hourly.data.names <- c("id",	"year",	"day",	"hour",	"mean.temp", "meanrh", "mean.leaf.wetness",
                        "rain.tot", "mean.grass.temp",	"min.grass.temp",	"mean.soil.temp", 
                        "min.soil.semp",	"solar.rad",	"wind.speed",	"wind.dir",	"pet")


hourly.data <- 
  read_csv(file.path(ExpData, 'OYB New hourly.csv'), 
           col_names = F) %>% 
  slice(-c(1:7)) %>% 
  select(1:16) %>%
  setNames(hourly.data.names) %>% 
  mutate_all(., funs(as.numeric(as.character(.)))) %>% 
  distinct(year,day,hour, .keep_all = T) 

glimpse(hourly.data)
# last(hourly.data$year)

```

# Check the missing data and replace missing value
```{r, fig.width=15, fig.height=25,echo=FALSE}
 

hourly.data.new <- 
   hourly.data %>% 
   mutate_at('solar.rad',funs(replace(., .< 0, 0))) %>% 
   mutate_at('meanrh',funs(replace(., .< 0, 0))) %>% 
   mutate_if(is.numeric,funs(replace(.,is.nan(.),NA))) %>% 
   group_by(day,hour) %>%
   mutate_at('solar.rad',funs(replace(.,is.na(.),mean(.,na.rm=TRUE))))%>%
   mutate_at('meanrh',funs(replace(.,is.na(.),mean(.,na.rm=TRUE))))%>%
   ungroup(.) %>% 
   distinct(year,day, hour, .keep_all = TRUE) %>% 
   mutate(mean.rh = if_else(meanrh > 100, 100, meanrh)) %>% 
   arrange(year,day,hour) %>% 
   select(year,day,hour, solar.rad, mean.rh, wind.speed) %>% 
   filter(year>= 2019) %>% 
   filter(!(year==2019 & day<=133))

glimpse(hourly.data.new)

short_summary(hourly.data.new)  

  # View(hourly.data.hourly)
```


# doing some calculations
```{r, fig.width=15, fig.height=25,echo=FALSE}
 
FPAR = 0.55
WATT_TO_PPFD = 4.55

hourly.data.daily.cal <-
  hourly.data.new %>% 
   arrange(year,day,hour) %>% 
  select(year, day, hour, solar.rad, mean.rh) %>% 
  # mutate(mean.solar.rad.j = as.numeric(meansolarradw.m2) ) %>% 
  group_by(year,day) %>% 
  summarise_all(mean, na.rm = TRUE) %>% 
  ungroup %>% 
  distinct(year,day, .keep_all = T) %>% 
  mutate(daily.solar.rad.mj.m2 = solar.rad * 3600 *24 /1e6 )

  
# glimpse(climate.data.daily.cal)

short_summary(hourly.data.daily.cal)  
     
write_csv(hourly.data.daily.cal, file.path(IntermediateResults, paste(output.name, '.daily.cal.csv',sep = '')))
  
```
