---
title: "Checking and tiding up the climate data"
author: "Junqi ZHU"
output:
  html_document: default
editor_options: 
  chunk_output_type: inline
  # step 1, copy the new hourly data to the five hourly file first. The existing file contains more data than the file directly copied from Rob each time
  # coping to the existing file ensure that we have a complete records of the meteo data
  # we may need to have a complete year as some calculations needs to update the step, like in the groimp model
  # step 2, do the calculations for the last year, we do not check the dates, just replace the whole year's data
  # step 3, add the new meteo data to the meteo_latest data
  # step 4, output the meteo_latest file
  # do the MRL first, as booker and squire need blenheim station's radiation, 
  # append other sites's data to the meteo_latest as well.
  
  #
---

```{r, warning=FALSE, echo=FALSE, tidy=TRUE, error=FALSE, message=FALSE}
 rm(list = ls())
    {
    library(plyr)
    l_ply(list('tidyverse','readxl','readr','tidyr','dplyr','ggplot2','broom','ggthemes','plotly','purrr',
               'reshape2','cowplot','grid', 'reshape2','lubridate', 'RColorBrewer', 'datacheck'), 
          require, character.only = T)
    # tidyverse_update(recursive = FALSE) #updating packages
    #get the current working directory
    MainDir <- list(PROJHOME = normalizePath(getwd()))
    # Input and output directory data file location
    ExpData = file.path(MainDir, 'ExpData')
    # figure output directory, mainly the the place for paper writing 
    FigureOutput = file.path(MainDir, 'Figures')
    
        
if(grepl('powerplant', MainDir) == T)
    {
    LibFunctions = file.path('/powerplant/workspace/hrmjxz/Programming_lang/R_language/Function_library/')
    } else if(grepl('/mnt/sda', MainDir) == T)
     {
    LibFunctions = file.path("/mnt/sda/Programming_lang/R_language/Function_library/")
    } else if(grepl('HRMLXY', MainDir) == T)
    {
      LibFunctions = file.path('//MAR-FILE//HOME$//HRMLXY/My 
                  Documents/GitHub/grapevine_yield_components/Customized function library')
    } else
    { LibFunctions = file.path("W:/Programming_lang/R_language/Function_library/") }
    
    
   
    # LibFunctions = file.path('E:/Programming_lang/R_language/Function_library/')
   # LibFunctions = file.path('/powerplant/workspace/hrmjxz/Programming_lang/R_language/Function_library/')
    IntermediateResults = file.path(MainDir, 'Intermediate results')  
    SupportingFunctions = file.path(MainDir, 'Supporting functions')
    # Load all functions
    source(file.path(LibFunctions,'Customized_functions_for_climate.R'))
    
    } 
```

# A remind of the subject that you are working on
```{r}
current.region <- 'MRL'
current.subject <- 'Hourly_New'

site = "Blenheim"
# keep year as numeric variable
lastYear = 2020
is.numeric(lastYear)
output.name <- paste(current.region, current.subject, sep = '_')
# glimpse(output.name)
```

## Load the data
```{r, warning=FALSE, echo=FALSE, error=FALSE, message=FALSE}
climate.data.names <- c('ID','Stn.No.','Year','Day','Hour','Mean.Ta','Mean.wet.bulb.',	'Mean.leaf.Wet',
                            'Total.Rain.mm.0.1','Grass.Min.Temp','Mean.10.cm.soil.temp',
                            'Mean.20.cm.soil.temp','Mean.30.cm.soil.temp','Mean.100.cm.soil.temp',
                            'Mean.Solar.Rad.w.m2','Mean.wind.speed.m.s', 'Mean.wind.direction.N','Total.Rain.mm.0.2',
                            'Mean.RH','Mean.Ta.back.up','Sunshine.min', 'Soil.Moisture','Penman.ET')
    
    

  climate.data <- read_csv(file.path(ExpData, 'Site_MRL_Hourly.csv')) %>% 
  select(1:23) %>% 
  slice(-c(1:6)) %>% 
  setNames(tolower(climate.data.names)) %>% 
  mutate_all(., funs( as.numeric(as.character(.)))) %>% 
  distinct(year,day,hour, .keep_all = T) %>% 
  filter(year>= lastYear) 
  # filter(!(year==2020 & day<=11))
  #   

glimpse(climate.data)
first(climate.data$year)
last(climate.data$year)

```

## create a complete records of days and hours

```{r, warning=FALSE, echo=FALSE, error=FALSE, message=FALSE}

first.day <- first(climate.data$day)
first.year <- first(climate.data$year)

last.day <- last(climate.data$day)
last.year <- last(climate.data$year)

start.date <- as.Date(first.day, origin = paste(first.year-1, 12, 31, sep = '-'))
end.date <- as.Date(last.day, origin = paste(last.year-1, 12, 31, sep = '-'))


yday(end.date)
chour <-c(0,100,200,300,400,500,600,700,800,900,1000,1100,1200,
          1300,1400,1500,1600,1700,1800,1900,2000,2100,2200,2300)

complete.year.day <- 
  data_frame(date = seq.Date(from = start.date,to = end.date, by = 'day')) %>% 
  mutate(year = year(date), day.of.year = yday(date)) 

 complete.year.day.hour<-  merge(complete.year.day,chour,all=TRUE)
 data.frame(complete.year.day.hour)
names (complete.year.day.hour) = c("date", "year", "day","hour")


glimpse(complete.year.day.hour)

```

# Check the missing data and replace missing value

```{r, fig.width=15, fig.height=25,echo=FALSE}

complete.hourly <- 
  right_join(climate.data, complete.year.day.hour, by = c('year','day', 'hour')) %>% 
   mutate_at('mean.solar.rad.w.m2',funs(replace(., .< 0, 0))) %>% 
   mutate_at('mean.rh',funs(replace(., .< 0, 0))) %>% 
   mutate_if(is.numeric,funs(replace(.,is.nan(.),NA))) %>% 
   group_by(day,hour) %>%
   mutate_at('mean.solar.rad.w.m2',funs(replace(.,is.na(.),mean(.,na.rm=TRUE))))%>%
   mutate_at('mean.rh',funs(replace(.,is.na(.),mean(.,na.rm=TRUE))))%>%
   mutate_at('mean.ta',funs(replace(.,is.na(.),mean(.,na.rm=TRUE))))%>%
   mutate_at('mean.wind.speed.m.s',funs(replace(.,is.na(.),mean(.,na.rm=TRUE))))%>%
   rename(total.rain = total.rain.mm.0.2) %>% 
   mutate_at('total.rain',funs(replace(.,is.na(.),0)))%>%
   mutate_at('total.rain',funs(replace(., . < 0 ,0)))%>%
   ungroup(.) %>% 
   mutate(mean.rh = if_else(mean.rh > 100, 100, mean.rh)) %>% 
   drop_na(year) %>% 
   mutate(vpd = VPD((mean.ta), mean.rh/100)) %>% 
   mutate(hour = hour/100) %>% 
   arrange(year, day, hour)
  
    
write_csv(complete.hourly, file.path(IntermediateResults, paste(output.name, '.csv',sep = '')))

#short_summary(complete.hourly)  

```

#summarise the data into daily data
```{r, fig.width=15, fig.height=25,echo=FALSE}

climate.data.daily.cal <- 
  complete.hourly %>% 
  
 # mutate( hour= if_else(hour==24, 0, hour)) %>% 
  arrange(year,day,hour) %>% 
  mutate(stn.no.=121 ) %>% 
  select(year, stn.no., day, hour, total.rain, mean.ta, mean.rh, 
         mean.solar.rad.w.m2,mean.wind.speed.m.s, vpd) %>% 
  group_by(year, day) %>% 
  summarise_all(list(mean=mean,min=min, max=max, sum=sum), na.rm = T) %>% 
  mutate(daily.solar.rad.mj.m2 = mean.solar.rad.w.m2_mean * 3600 *24 /1e6 ) %>%
  select(year, day, total.rain_sum, mean.ta_max, mean.ta_min,mean.ta_mean,
         daily.solar.rad.mj.m2, mean.wind.speed.m.s_mean, mean.rh_mean, vpd_mean) %>% 
  rename(Tmin = mean.ta_min, 
         Tmax = mean.ta_max,
         Tmean = mean.ta_mean,
         totalRain = total.rain_sum,
         Rad = daily.solar.rad.mj.m2, 
         RH  = mean.rh_mean,
         Wind = mean.wind.speed.m.s_mean,
         vpd = vpd_mean) %>% 
  mutate(ET0 = calcDailyET0(Rad, Tmean, Wind, vpd)) %>% 
  mutate(ET_Rain = ET0 - totalRain) %>% 
  mutate(station = site) %>% 
  mutate(vineyard = case_when(station == "Blenheim" ~ "NA",
                             TRUE ~ station)) %>% 
  mutate(region = "Marlborough") %>% 
  rename(doy = day) %>% 
  filter(year >=lastYear)

head(climate.data.daily.cal)
tail(climate.data.daily.cal)

write_csv(climate.data.daily.cal, 
          file.path(IntermediateResults, paste(output.name, '.daily.cal.csv',sep = '')))
#names(complete.hourly)
  
```


## Load the organized data
```{r, warning=FALSE, echo=FALSE, error=FALSE, message=FALSE}

 daily.data <- 
  read_csv(file.path(IntermediateResults, 'MetData_latest.csv'),guess_max = 1000) %>% 
  arrange(station, year, doy) %>% 
  filter(!(station == site & year >= lastYear))


daily.data %>% 
  filter((station == site & year == (lastYear-1))) %>% 
  tail()


daily.data %>% 
    filter((station == site && year > lastYear))
   
 
glimpse(daily.data)

```

#join the data
```{r, fig.width=15, fig.height=25,echo=FALSE}

full.data <- 
    bind_rows(daily.data, climate.data.daily.cal) 
 
# short_summary(full.data)
 
write_csv(full.data, file.path(IntermediateResults, 'MetData_latest.csv'))

# write_tsv(full.data, file.path(IntermediateResults, paste(output.name, "met", sep = '.')))

```

