---
title: "Checking and tiding up the climate data"
author: "Junqi ZHU"
output:
  html_document: default
---

```{r, warning=FALSE, echo=FALSE, tidy=TRUE, error=FALSE, message=FALSE}
 rm(list = ls())
    {
    library(plyr)
    l_ply(list('tidyverse','readxl','tidyr','readr','dplyr','ggplot2','broom','ggthemes','plotly','purrr',
               'reshape2','cowplot','grid', 'reshape2','lubridate', 'RColorBrewer', 'datacheck'), 
          require, character.only = T)
    # tidyverse_update(recursive = FALSE) #updating packages
    #get the current working directory
    MainDir <- list(PROJHOME = normalizePath(getwd()))
    # Input and output directory data file location
    ExpData = file.path(MainDir, 'ExpData')
    # figure output directory, mainly the the place for paper writing 
    FigureOutput = file.path(MainDir, 'Figures')
    
    # Output directory, final results except figures, like statistics, and intermediate data set
    IntermediateResults = file.path(MainDir, 'Intermediate results')  
    SupportingFunctions = file.path(MainDir, 'Supporting functions')
    # CustomizedFunctions = file.path('d:/Programming language/R language/Customized function library/')
    CustomizedFunctions = file.path(MainDir, 'customizedFunctionsLib')
    
    # Load all functions
    source(file.path(CustomizedFunctions,'Customized_curve_fitting_functions.R'))
    source(file.path(CustomizedFunctions,'Customized_functions_data_reconstruction.R'))
    
    source(file.path(SupportingFunctions,'Layout_of_ggplot.R'))
    source(file.path(SupportingFunctions,'Specific_functions.R'))
    # lsf.str()  #list of functions
    } 
```

# A remind of the subject that you are working on
```{r}
current.region <- 'Site1002_OYB'
current.subject <- 'Hourly_New'
# current.year <- '18_19'

output.name <- paste(current.region, current.subject, sep = '_')
output.name

```

## Load the data
```{r, warning=FALSE, echo=FALSE, error=FALSE, message=FALSE}
options(dplyr.width = Inf, dplyr.print_min = 10)

hourly.data.names <- c("id",	"year",	"day",	"hour",	"mean.temp", "meanrh", "mean.leaf.wetness",
                        "rain.tot", "mean.grass.temp",	"min.grass.temp",	"mean.soil.temp", 
                        "min.soil.semp",	"solar.rad",	"wind.speed",	"wind.dir",	"pet")


hourly.data <- 
  read_csv(file.path(ExpData, 'Site1002_OYB_Hourly.csv'), 
           col_names = F) %>% 
  slice(-c(1:7)) %>% 
  select(1:16) %>%
  setNames(hourly.data.names) %>% 
  mutate_all(., funs(as.numeric(as.character(.)))) %>% 
  distinct(year,day,hour, .keep_all = T) 

glimpse(hourly.data)
# last(hourly.data$year)

```

## create a complete records of days and hours

```{r, warning=FALSE, echo=FALSE, error=FALSE, message=FALSE}

first.day <- first(hourly.data$day)
first.year <- first(hourly.data$year)

last.day <- last(hourly.data$day)
last.year <- last(hourly.data$year)

start.date <- as.Date(first.day, origin = paste(first.year-1, 12, 31, sep = '-'))
end.date <- as.Date(last.day, origin = paste(last.year-1, 12, 31, sep = '-'))


yday(end.date)
chour <-c(0,100,200,300,400,500,600,700,800,900,1000,1100,1200,
          1300,1400,1500,1600,1700,1800,1900,2000,2100,2200,2300)

complete.year.day <- 
  data_frame(date = seq.Date(from = start.date,to = end.date, by = 'day')) %>% 
  mutate(year = year(date), day.of.year = yday(date)) 

 complete.year.day.hour<-  merge(complete.year.day,chour,all=TRUE)
 data.frame(complete.year.day.hour)
names (complete.year.day.hour) = c("date", "year", "day","hour")


glimpse(complete.year.day.hour)

```

# Check the missing data and replace missing value
```{r, fig.width=15, fig.height=25,echo=FALSE}

names(hourly.data) = c("stn.no.","year", "day" ,   "hour" ,    "mean.ta"  ,      
"mean.rh" ,           "mean.leaf.wetness", "rain.tot" ,         "mean.grass.temp",   "min.grass.temp",   
"mean.soil.temp",    "min.soil.semp" ,    "mean.solar.rad.w.m2" ,        "mean.wind.speed.m.s"  ,      "wind.dir" ,        
 "pet")
complete.hourly <- 
  right_join(hourly.data, complete.year.day.hour, by = c('year','day', 'hour')) %>% 
   mutate_at('mean.solar.rad.w.m2',funs(replace(., .< 0, 0))) %>% 
  mutate_at('mean.ta',funs(replace(., .< -10, NA))) %>% 
   mutate_at('mean.rh',funs(replace(., .< 0, 0))) %>% 
   mutate_if(is.numeric,funs(replace(.,is.nan(.),NA))) %>% 
   group_by(day,hour) %>%
   mutate_at('mean.solar.rad.w.m2',funs(replace(.,is.na(.),mean(.,na.rm=TRUE))))%>%
   mutate_at('mean.rh',funs(replace(.,is.na(.),mean(.,na.rm=TRUE))))%>%
   mutate_at('mean.ta',funs(replace(.,is.na(.),mean(.,na.rm=TRUE))))%>%
   mutate_at('mean.wind.speed.m.s',funs(replace(.,is.na(.),mean(.,na.rm=TRUE))))%>%
   ungroup(.) %>% 
   mutate(mean.rh = if_else(mean.rh > 100, 100, mean.rh)) %>% 
  drop_na(year)
   #names(climate.data.hourly)

  # glimpse(climate.data.hourly)
#write.csv(complete.hourly, file.path(IntermediateResults, paste(output.name, '.csv',sep = '')))

  

#names(hourly.data)

  # View(hourly.data.hourly)
```


# organize the data for input into GroIMP
```{r, fig.width=15, fig.height=25,echo=FALSE}
 

FPAR = 0.55
WATT_TO_PPFD = 4.55
    
date = as.Date("2019-2-04")
yday(date)
leap_year(2019)
  
climate.data.hourly.new <- 
  complete.hourly %>% 
  mutate(hour = hour/100) %>% 
  mutate( hour= if_else(hour==24, 0, hour)) %>% 
  arrange(year,day,hour) %>% 
  mutate(total.radiation.umol.m2.s = as.numeric(mean.solar.rad.w.m2) * WATT_TO_PPFD) %>%
  mutate(mean.wind.speed.m.s=as.numeric(mean.wind.speed.m.s)) %>% 
   mutate(mean.ta=as.numeric(mean.ta)) %>% 
  mutate(stn.no.=60) %>%
  mutate(CO2.ppm = 400, swp.MPa = -0.2, mean.rh = mean.rh/100) %>% 
  
  select(day, hour, mean.ta, mean.rh,total.radiation.umol.m2.s,CO2.ppm, mean.wind.speed.m.s, swp.MPa, year, stn.no.) #%>%
  #filter((year == 2019))
    
write_csv(climate.data.hourly.new, file.path(IntermediateResults, 
                    paste('OYB.climate.data.hourly.csv',sep = '')))  
range(climate.data.hourly.new$mean.ta)

#names(hourly.data.new)
  
````        
  
